[package]
name = "my_lambda_func"
version = "0.1.0"
authors = ["Damien Pontifex <damien.pontifex@gmail.com>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "bootstrap"

[dependencies]
lambda_runtime = "0.3"
aws_lambda_events = "0.4"
tokio = { version = "1", features = ["macros", "rt"] }
